name: Update Versions

on:
  workflow_dispatch:
    inputs:
      branchVersion:
        description: 'Branch version number'
        required: true
      packageVersion:
        description: 'Package version number'
        required: true
      manifestVersion:
        description: 'Manifest version number'
        required: true

jobs:
  update-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Checkout Actions
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Install dependencies
        run: npm ci

      - name: Update Runtime Version
        run: node scripts/update-versions.js *.manifest.*.json manifest.*.json runtime ${{ github.events.inputs.manifestVersion }}

      - name: Update Package & Adapter Version
        run: node scripts/update-versions.js package.json devDependencies ${{ github.events.inputs.packageVersion }}

      - name: Update main repo version
        run: node scripts/update-versions.js package.json version ${{ github.events.inputs.packageVersion }}

      - name: Create New Branch 
        run: git checkout -b ${{ github.event.inputs.branchVersion }} && git push origin ${{ github.event.inputs.branchVersion }}
