name: Update Versions

on:
  workflow_dispatch:
    inputs:
      branchVersion:
        description: 'Branch version number'
        required: true
      packageVersion:
        description: 'Package version number'
        required: true
      manifestVersion:
        description: 'Manifest version number'
        required: true

jobs:
  update-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Checkout Actions
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      
      - name: Install dependencies
        run: npm ci

      - name: Update Runtime Version
        run: node scripts/update-versions.js *.manifest.*.json manifest.*.json *.fin.json runtime ${{ inputs.manifestVersion }}

      - name: Update Package & Adapter Version
        run: node scripts/update-versions.js package.json devDependencies ${{ inputs.packageVersion }}

      - name: Update main repo version
        run: node scripts/update-versions.js package.json version ${{ inputs.packageVersion }}
      
      - name: setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "adam.saland@openfin.co"
      
      - name: Create New Branch 
        run: git checkout -b ${{ inputs.branchVersion }} && git add --all && git commit -m "bump version to ${{ inputs.branchVersion }}" && git push origin ${{ inputs.branchVersion }}
