name: Update Versions

on:
  workflow_dispatch:
    inputs:
      branchVersion:
        description: 'Branch version number'
        required: true
      packageVersion:
        description: 'Package version number'
        required: true
      manifestVersion:
        description: 'Manifest version number'
        required: true

jobs:
  create-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Replace Package Version
      - run: |
          find . -name "package.json" -type f -exec sed -i "s/\"version\": \".*\"/\"version\": \"${{ github.event.inputs.packageVersion }}\"/g" {} \;
      - name: Replace Manifest Version
      - run: |
          find . -type f \( -name "*.manifest.*.json" -o -name "manifest.*.json" \) -exec sed -i "s/\"runtime\":\s*{\s*\"version\":\s*\".*\"\s*}/\"runtime\":{\"version\":\"${{ github.event.inputs.manifestVersion }}\"}/g" {} \;
      - name: Create Branch
      - uses: actions/checkout@v2
        run: |
          git checkout -b ${{ github.event.inputs.branchVersion }}
          git push origin ${{ github.event.inputs.branchVersion }}
